

version: "3"
services:
  postgres:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: mydb
      TZ: Asia/Tokyo
    ports:
      - 5433:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
volumes:
  data:
